# 项目相关配置
oversea:
  # 名称
  name: oversea
  # 版本
  version: 2.7.9
  # 作者
  author: li_henggong
  # 年份
  copyrightYear: 2023

# 开发环境配置
server:
  # 服务器的HTTP端口号
  port: 80
  #servlet:
    # 应用的访问路径
    #context-path: /OverseasPurchasing
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
    #请求头最大长度kb
    max-http-header-size: 1048576
    #请请求体最大长度kb ,HTTP POST内容最大长度，默认不限制
    max-http-form-post-size: -1

# mybatis配置
mybatis:
  # 搜索指定别名包
  typeAliasesPackage: com.lhg.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# Spring配置
spring:
  profiles:
    active: druid

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api