# 项目相关配置
oversea:
  # 名称
  name: oversea
  # 版本
  version: 2.7.9
  # 作者
  author: li_henggong
  # 年份
  copyrightYear: 2023

# 开发环境配置
server:
  # 服务器的HTTP端口号
  port: 2910
  servlet:
    # 应用的访问路径
    context-path: /OverseasPurchasing

# mybatis配置
mybatis:
  # 搜索指定别名包
  typeAliasesPackage: com.lhg.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# Spring配置
